INSERT INTO [UserProfile]
VALUES	('testuser', 'test@test.test', getdate(), 'fPKy4nQKRbWKfRvEIbIsFACSxVs2'),  
		('iamdrewkirkland', 'test@test.com', getdate(),'IYgjFoDATFXu0PrdEgwR9sp4WwX2'),
		('iamnotdrewkirkland', 'test@test.net', getdate(), 'V5IPMlvwuRQmzivkXGuiX7ial392'),
		('joeschmoe', 'test@test.org', getdate(), 'nrwJfjVJadaWmwe8cbmrROOJKmC3')

INSERT INTO [Categories]
VALUES  ('Favorites', 1, '#990099', 1, 1),
		('YouTube', 1, null, 0, 1),
		('Cooking', 1, null, 0, 0),
		('Favorite Memes', 2, null, 1, 1),
		('Programming Links', 2, null, 1, 1)

insert into Links (Title, Url, CreateDate, UserProfileId, CategoryId, IsFavorite) values ('Keylex', 'https://blogger.com/montes/nascetur/ridiculus/mus.xml?lacus=quam&at=sapien&velit=varius&vivamus=ut&vel=blandit&nulla=non&eget=interdum&eros=in&elementum=ante&pellentesque=vestibulum&quisque=ante&porta=ipsum&volutpat=primis&erat=in&quisque=faucibus&erat=orci&eros=luctus&viverra=et&eget=ultrices&congue=posuere', '6/2/2020', 1, 3, 1);
insert into Links (Title, Url, CreateDate, UserProfileId, CategoryId, IsFavorite) values ('Lotlux', 'http://netlog.com/ut/blandit/non/interdum/in.png?sed=diam&vestibulum=vitae&sit=quam&amet=suspendisse&cursus=potenti&id=nullam&turpis=porttitor&integer=lacus&aliquet=at', '9/22/2019', 2, 4, 0);
insert into Links (Title, Url, CreateDate, UserProfileId, CategoryId, IsFavorite) values ('Zontrax', 'http://hhs.gov/arcu/sed/augue/aliquam/erat/volutpat.jpg?pede=diam&posuere=cras&nonummy=pellentesque&integer=volutpat&non=dui&velit=maecenas&donec=tristique&diam=est&neque=et&vestibulum=tempus&eget=semper&vulputate=est&ut=quam&ultrices=pharetra&vel=magna&augue=ac&vestibulum=consequat&ante=metus&ipsum=sapien&primis=ut&in=nunc&faucibus=vestibulum&orci=ante&luctus=ipsum&et=primis&ultrices=in&posuere=faucibus&cubilia=orci&curae=luctus&donec=et&pharetra=ultrices&magna=posuere&vestibulum=cubilia&aliquet=curae&ultrices=mauris&erat=viverra&tortor=diam&sollicitudin=vitae&mi=quam&sit=suspendisse&amet=potenti&lobortis=nullam&sapien=porttitor&sapien=lacus&non=at&mi=turpis&integer=donec&ac=posuere&neque=metus&duis=vitae&bibendum=ipsum', '8/6/2019', 2, 4, 1);
insert into Links (Title, Url, CreateDate, UserProfileId, CategoryId, IsFavorite) values ('Latlux', 'https://uiuc.edu/venenatis/lacinia/aenean/sit.html?accumsan=ridiculus&felis=mus&ut=vivamus&at=vestibulum&dolor=sagittis&quis=sapien&odio=cum&consequat=sociis&varius=natoque&integer=penatibus&ac=et&leo=magnis&pellentesque=dis&ultrices=parturient&mattis=montes&odio=nascetur&donec=ridiculus&vitae=mus&nisi=etiam&nam=vel&ultrices=augue&libero=vestibulum&non=rutrum&mattis=rutrum&pulvinar=neque&nulla=aenean&pede=auctor&ullamcorper=gravida&augue=sem&a=praesent&suscipit=id&nulla=massa&elit=id&ac=nisl&nulla=venenatis&sed=lacinia&vel=aenean&enim=sit&sit=amet&amet=justo&nunc=morbi&viverra=ut&dapibus=odio&nulla=cras&suscipit=mi&ligula=pede&in=malesuada&lacus=in&curabitur=imperdiet&at=et&ipsum=commodo&ac=vulputate&tellus=justo&semper=in&interdum=blandit&mauris=ultrices&ullamcorper=enim&purus=lorem&sit=ipsum&amet=dolor&nulla=sit&quisque=amet&arcu=consectetuer&libero=adipiscing&rutrum=elit&ac=proin&lobortis=interdum&vel=mauris&dapibus=non&at=ligula&diam=pellentesque&nam=ultrices&tristique=phasellus&tortor=id&eu=sapien', '10/27/2019', 2, 4, 1);
insert into Links (Title, Url, CreateDate, UserProfileId, CategoryId, IsFavorite) values ('Flexidy', 'http://ed.gov/imperdiet/nullam/orci/pede/venenatis.html?a=magna&libero=vestibulum&nam=aliquet&dui=ultrices&proin=erat&leo=tortor&odio=sollicitudin&porttitor=mi&id=sit&consequat=amet&in=lobortis&consequat=sapien&ut=sapien&nulla=non&sed=mi&accumsan=integer&felis=ac&ut=neque&at=duis&dolor=bibendum&quis=morbi&odio=non&consequat=quam&varius=nec&integer=dui&ac=luctus&leo=rutrum&pellentesque=nulla&ultrices=tellus&mattis=in&odio=sagittis&donec=dui&vitae=vel&nisi=nisl&nam=duis&ultrices=ac&libero=nibh&non=fusce&mattis=lacus&pulvinar=purus&nulla=aliquet&pede=at&ullamcorper=feugiat&augue=non&a=pretium&suscipit=quis&nulla=lectus&elit=suspendisse&ac=potenti&nulla=in&sed=eleifend&vel=quam&enim=a&sit=odio&amet=in&nunc=hac&viverra=habitasse&dapibus=platea&nulla=dictumst&suscipit=maecenas&ligula=ut&in=massa&lacus=quis&curabitur=augue&at=luctus&ipsum=tincidunt&ac=nulla&tellus=mollis&semper=molestie&interdum=lorem&mauris=quisque&ullamcorper=ut&purus=erat&sit=curabitur&amet=gravida&nulla=nisi&quisque=at&arcu=nibh', '1/1/2020', 2, 5, 1);
insert into Links (Title, Url, CreateDate, UserProfileId, CategoryId, IsFavorite) values ('Stronghold', 'https://wordpress.org/orci/pede/venenatis/non/sodales.xml?pede=eget&justo=tempus&eu=vel&massa=pede&donec=morbi&dapibus=porttitor&duis=lorem&at=id&velit=ligula&eu=suspendisse&est=ornare&congue=consequat&elementum=lectus&in=in&hac=est&habitasse=risus&platea=auctor&dictumst=sed&morbi=tristique&vestibulum=in&velit=tempus&id=sit&pretium=amet&iaculis=sem&diam=fusce&erat=consequat&fermentum=nulla&justo=nisl&nec=nunc&condimentum=nisl&neque=duis&sapien=bibendum&placerat=felis&ante=sed&nulla=interdum&justo=venenatis&aliquam=turpis&quis=enim&turpis=blandit&eget=mi&elit=in&sodales=porttitor&scelerisque=pede&mauris=justo&sit=eu&amet=massa&eros=donec&suspendisse=dapibus&accumsan=duis&tortor=at&quis=velit&turpis=eu&sed=est&ante=congue&vivamus=elementum&tortor=in&duis=hac&mattis=habitasse&egestas=platea&metus=dictumst&aenean=morbi&fermentum=vestibulum&donec=velit&ut=id&mauris=pretium&eget=iaculis&massa=diam&tempor=erat&convallis=fermentum&nulla=justo&neque=nec&libero=condimentum', '3/1/2020', 1, 1, 0);
insert into Links (Title, Url, CreateDate, UserProfileId, CategoryId, IsFavorite) values ('Otcom', 'https://1688.com/amet/consectetuer/adipiscing/elit/proin/interdum.xml?quis=at&tortor=velit&id=eu&nulla=est&ultrices=congue&aliquet=elementum&maecenas=in&leo=hac&odio=habitasse&condimentum=platea&id=dictumst&luctus=morbi&nec=vestibulum&molestie=velit&sed=id&justo=pretium&pellentesque=iaculis&viverra=diam&pede=erat&ac=fermentum&diam=justo&cras=nec&pellentesque=condimentum&volutpat=neque&dui=sapien&maecenas=placerat&tristique=ante&est=nulla&et=justo&tempus=aliquam&semper=quis&est=turpis&quam=eget&pharetra=elit&magna=sodales&ac=scelerisque&consequat=mauris', '5/13/2020', 1, 2, 1);
insert into Links (Title, Url, CreateDate, UserProfileId, CategoryId, IsFavorite) values ('Treeflex', 'http://arizona.edu/vel/pede/morbi.xml?leo=tincidunt&rhoncus=nulla&sed=mollis&vestibulum=molestie&sit=lorem&amet=quisque&cursus=ut&id=erat&turpis=curabitur&integer=gravida&aliquet=nisi&massa=at&id=nibh&lobortis=in&convallis=hac&tortor=habitasse&risus=platea&dapibus=dictumst&augue=aliquam&vel=augue&accumsan=quam&tellus=sollicitudin&nisi=vitae&eu=consectetuer&orci=eget&mauris=rutrum&lacinia=at&sapien=lorem&quis=integer&libero=tincidunt&nullam=ante&sit=vel&amet=ipsum&turpis=praesent&elementum=blandit&ligula=lacinia&vehicula=erat&consequat=vestibulum&morbi=sed&a=magna&ipsum=at&integer=nunc&a=commodo&nibh=placerat&in=praesent&quis=blandit&justo=nam&maecenas=nulla&rhoncus=integer&aliquam=pede&lacus=justo&morbi=lacinia&quis=eget&tortor=tincidunt&id=eget&nulla=tempus&ultrices=vel&aliquet=pede', '6/30/2020', 2, 5, 1);
insert into Links (Title, Url, CreateDate, UserProfileId, CategoryId, IsFavorite) values ('Regrant', 'http://themeforest.net/libero/rutrum/ac.jsp?pede=neque&libero=sapien&quis=placerat&orci=ante&nullam=nulla&molestie=justo&nibh=aliquam&in=quis&lectus=turpis&pellentesque=eget&at=elit&nulla=sodales&suspendisse=scelerisque&potenti=mauris&cras=sit&in=amet&purus=eros&eu=suspendisse&magna=accumsan&vulputate=tortor&luctus=quis&cum=turpis&sociis=sed&natoque=ante&penatibus=vivamus&et=tortor&magnis=duis&dis=mattis&parturient=egestas&montes=metus&nascetur=aenean&ridiculus=fermentum&mus=donec&vivamus=ut&vestibulum=mauris&sagittis=eget&sapien=massa&cum=tempor&sociis=convallis&natoque=nulla&penatibus=neque&et=libero&magnis=convallis&dis=eget', '6/27/2020', 1, 3, 0);
insert into Links (Title, Url, CreateDate, UserProfileId, CategoryId, IsFavorite) values ('Konklux', 'http://123-reg.co.uk/sit.aspx?maecenas=cubilia&leo=curae&odio=donec&condimentum=pharetra&id=magna&luctus=vestibulum&nec=aliquet&molestie=ultrices&sed=erat&justo=tortor&pellentesque=sollicitudin&viverra=mi&pede=sit&ac=amet&diam=lobortis&cras=sapien&pellentesque=sapien&volutpat=non&dui=mi&maecenas=integer&tristique=ac&est=neque&et=duis&tempus=bibendum&semper=morbi&est=non&quam=quam&pharetra=nec&magna=dui&ac=luctus&consequat=rutrum&metus=nulla&sapien=tellus&ut=in&nunc=sagittis&vestibulum=dui&ante=vel&ipsum=nisl&primis=duis&in=ac&faucibus=nibh&orci=fusce&luctus=lacus&et=purus&ultrices=aliquet&posuere=at&cubilia=feugiat&curae=non&mauris=pretium&viverra=quis&diam=lectus&vitae=suspendisse&quam=potenti&suspendisse=in&potenti=eleifend&nullam=quam&porttitor=a&lacus=odio&at=in&turpis=hac&donec=habitasse&posuere=platea&metus=dictumst&vitae=maecenas&ipsum=ut&aliquam=massa&non=quis&mauris=augue&morbi=luctus&non=tincidunt&lectus=nulla&aliquam=mollis&sit=molestie&amet=lorem&diam=quisque&in=ut&magna=erat&bibendum=curabitur&imperdiet=gravida&nullam=nisi&orci=at&pede=nibh&venenatis=in&non=hac&sodales=habitasse&sed=platea&tincidunt=dictumst&eu=aliquam&felis=augue&fusce=quam&posuere=sollicitudin&felis=vitae', '7/19/2020', 2, 5, 1);

INSERT INTO [UserApprovedList]
VALUES  (1, 2),
		(1, 3),
		(1, 4)
